### ISSUE TITLE
Failed to generate diagram

### ISSUE THREAD

**Issue by or-goldfus-confetti** [microsoft/vscode-mermAId#81]
Type: <b>Bug</b>

I asked it to update the diagram and it failed, which I understand, but the output is really not helpfull.

last few relevant lines from the response:
```
The error is due to the missing arrow type in the line ECS->>ECS: handleCalendarUpdates(events, syncTime). I will fix it by adding the correct arrow type.

The issue is caused by the line break in the else block. Here is the corrected diagram:

Failed to display your requested mermaid diagram. Check output log for details.
```

Extension version: 0.0.2024103001
VS Code version: Code 1.95.0 (Universal) (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id f179b36e-087f-4fc4-901d-62deae785a86|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31156133
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by joshspicer** [comment]
Thank you for the report.  For larger files we sometimes see the LLM produce mermaid diagrams with invalid characters.  We attempt to catch this by parsing the mermaid, grabbing the error as JSON, and feeding that back into the LLM with instructions to try again.

Would you mind sharing some information about your project (programming language, number of lines of code in the file, etc) so we can try to improve this parse handling for your specific scenario?

**Comment by or-goldfus-confetti** [comment]
Hi @joshspicer, sorry for the delay, I was OOO last week.
I must say that what bothered me the most was "Check output log for details".
I know this extension (and the entire LLM ecosystem 😅) is in its early days and I expect failures to occur, but it would be nice to see the details of what went wrong. So I think that it might be helpful to add instructions for where to find the aforementioned log file.

Regarding your question, the project is a large Nest project (TS), and I provided multiple files as context (~5), varying from ~50 LOC to ~650 LOC.

**Comment by joshspicer** [comment]
Thanks for the feedback.  The output log is in standard spot in VS Code, but I understand it was not clear from that message

For the future, you can find it under `Output`:

![Image](https://github.com/user-attachments/assets/53ba0ed8-38c6-4576-9029-03d2013abe46)
